services:
  redis:
    image: redis:latest
    container_name: redis_app
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - share_network

volumes:
  redis_data:

networks:
  share_network:
    external: true